"""add user preferences_json column

Revision ID: 09b0fa622dad
Revises: b9aa1d5df7c4
Create Date: 2026-01-13 17:17:55.818885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b0fa622dad'
down_revision = 'b9aa1d5df7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences_json')

    # ### end Alembic commands ###
