"""Add categories table with relationship to vouchers, add fk category_id to vouchers table, remove category column

Revision ID: 94b7d1265134
Revises: bd785b29a070
Create Date: 2025-12-05 20:53:01.229418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b7d1265134'
down_revision = 'bd785b29a070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vouchers_category_id', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_vouchers_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
