"""Add attachments table

Revision ID: b3e57bec99a6
Revises: f43393c70a7e
Create Date: 2025-12-09 22:32:54.138587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e57bec99a6'
down_revision = 'f43393c70a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.VARCHAR(length=120), nullable=True))

    op.drop_table('attachments')
    # ### end Alembic commands ###
