"""Add attachment and date received column to DV model

Revision ID: bef98464665b
Revises: d30967cf03cc
Create Date: 2025-12-02 08:57:06.533919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef98464665b'
down_revision = 'd30967cf03cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('date_received', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('date_received')
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
