"""Add Disbursement Voucher model

Revision ID: d30967cf03cc
Revises: 98f40be44928
Create Date: 2025-11-27 12:43:19.445629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30967cf03cc'
down_revision = '98f40be44928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dv_number', sa.String(length=20), nullable=True),
    sa.Column('mode_of_payment', sa.Enum('Cash', 'Check', 'Others', name='mode_of_payment'), nullable=True),
    sa.Column('payee', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('obr_number', sa.String(length=20), nullable=True),
    sa.Column('resp_center', sa.String(length=20), nullable=True),
    sa.Column('particulars', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dv_number'),
    sa.UniqueConstraint('obr_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vouchers')
    # ### end Alembic commands ###
