"""Add a table for the responsibility center

Revision ID: f43393c70a7e
Revises: 85768807a007
Create Date: 2025-12-07 20:25:14.463882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43393c70a7e'
down_revision = '85768807a007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsibility_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resp_center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vouchers_resp_center_id', 'responsibility_centers', ['resp_center_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('resp_center')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resp_center', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_vouchers_resp_center_id', type_='foreignkey')
        batch_op.drop_column('resp_center_id')

    op.drop_table('responsibility_centers')
    # ### end Alembic commands ###
